// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lykuudxovypsfzixbiuc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imx5a3V1ZHhvdnlwc2Z6aXhiaXVjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDUwNDI3MzUsImV4cCI6MjA2MDYxODczNX0.74YFgF4Yp-nSmS2cVZ1HqdHEPu27zrWqvjMSKN0tW0M";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);